### ISSUE TITLE
Syslinux

### ISSUE THREAD

**Issue by JonnyTech** [oneohthree/bootify#2]
Can the following be replaced by syslinux:

>   BTS="res/bootstrap"
>     dd if=$BTS of=$DEV > /dev/null 2>&1 || { echo "Error injecting bootstrap" 1>&2; exit 1; }

Example command:

> dd if=/usr/lib/extlinux/mbr.bin of=/dev/sda bs=440 count=1

That will just rely on the script rather than also having a binary file included.

**Comment by oneohthree** [comment]
Sorry to be VERY late. I like this approach, but we have to rely on mbr.bin file possible locations.

**Comment by oneohthree** [comment]
Solved in 5222bb1cbc10f0cfb742ec27b9fc4c15eaccdbe8 no need for syslinux.

**Comment by JonnyTech** [comment]
Nice self contained solution, although horrible to edit!

**Comment by oneohthree** [comment]
I agree, but I think this is better than having the file included.
