### ISSUE TITLE
Feature : use rsync instead of cp to view the progression

### ISSUE THREAD

**Issue by sebma** [oneohthree/bootify#3]
Hi,

First, let me congratulate for this great tool !

Why not use `rsync` instead of `cp` ?

To copy to a NTFS system, I use this command : 

`rsyncCP -pr /tmp/src/ /media/$USER/Win7_USB_Installer/`

where `rsyncCP` is an alias to `time \rsync -uth -P -z -v`

To copy to a FAT32, I use this command : 

`rsyncCP -r  --size-only /tmp/src/ /media/$USER/Win7_USB_Installer/`

**Comment by oneohthree** [comment]
Thanks!
My intention was to use something more generic (every Linux distribution has `cp` available), in fact I use `rsync` myself, it's more verbose and powerful.

**Comment by oneohthree** [comment]
Well, in my experience I had to install `rsync` on several distributions. `cp` is part of the shell.

**Comment by sebma** [comment]
Maybe on server distributions but anyway.

There are other tools like `gcp` or `pv`, but one has to install them also.

I find it difficult to implement the copy progression in shell without using an extra tool,  why not use `rsync -P` which is kind of standard ?

and why not add this `rsync` tool to your script dependencies in the `checks` function ?

**Comment by oneohthree** [comment]
Done in 119fdf28c7c0f6c8ce28e3ed1049dc2b04e0dd08
Thanks for your support.

**Comment by sebma** [comment]
Thanks a lot :-)
