### ISSUE TITLE
Question : Why are your mbr.bin and /usr/lib/syslinux/mbr.bin file different

### ISSUE THREAD

**Issue by sebma** [oneohthree/bootify#6]
Hi,

Why are your mbr.bin and /usr/lib/syslinux/mbr.bin file different ?

```
$  diff /tmp/mbr.bin /usr/lib/syslinux/mbr.bin 
Binary files /tmp/mbr.bin and /usr/lib/syslinux/mbr.bin differ
```
Does one provide different functionalities over the other ?

**Comment by yeniermc** [comment]
The MBR provided is the one from Microsoft. I wrote it with Microsoft tool, then I dumped it using `dd`. You can verify if you want it. There are no special functionalities using either.

**Comment by oneohthree** [comment]
The MBR provided is the one from Microsoft. I wrote it with Microsoft tool, then I dumped it using dd. You can verify if you want it. There are no special functionalities using either.
